services:

  frontend:
    build: ./frontend-sigmotos
    container_name: frontend-sigmotos
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-sigmotos:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - sigmotos-network

  postgres:
    image: postgres:16
    container_name: sigmotos-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

    networks:
      - sigmotos-network

  discovery-service:
    build:
      context: ./backend-sigmotos/discovery-service

    container_name: discovery-service

    ports:
      - "8761:8761"

    networks:
      - sigmotos-network

  api-gateway:
    build:
      context: ./backend-sigmotos/api-gateway

    container_name: api-gateway

    ports:
      - "8090:8080"

    depends_on:
      - discovery-service

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

    networks:
      - sigmotos-network

  users-service:
    build:
      context: ./backend-sigmotos/users-service

    container_name: users-service

    ports:
      - "8081:8081"

    depends_on:
      - postgres
      - discovery-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

    networks:
      - sigmotos-network

  inventory-service:
    build:
      context: ./backend-sigmotos/inventory-service

    container_name: inventory-service

    ports:
      - "8082:8082"

    depends_on:
      - postgres
      - discovery-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

    networks:
      - sigmotos-network

  workshop-service:
    build:
      context: ./backend-sigmotos/workshop-service

    container_name: workshop-service

    ports:
      - "8083:8083"

    depends_on:
      - postgres
      - discovery-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workshop_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

    networks:
      - sigmotos-network

  ocr-service:
    build:
      context: ./backend-sigmotos/ocr-service

    container_name: ocr-service

    ports:
      - "8084:8084"

    depends_on:
      - discovery-service

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

    networks:
      - sigmotos-network

volumes:
  postgres_data:

networks:
  sigmotos-network: